### ISSUE TITLE
Use a Jan atmosphere restart for a better match with forcing

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/dev_coupling#16]
Current suite, e.g. u-db245, starts from Jan 1 but is using the Sept 1 UM restart file `/g/data/access/TIDS/OCEAN/hadgem3/initial/atmos/N96L85/ab357a.da19810901_00`. This is because the suite was derived from a Met Office AMIP suite which conventionally starts in September.

**Comment by MartinDix** [comment]
Used Jan restart from the GAL9 AMIP6 run `anitial=u-cv124 /g/data/p66/mrd599/cv124a.da19820101_00`. Also requires change to 
`model_basis_time=1981,01,01,00,00,00`

Model ran as before, ok with `calc_tsfc = .true.`, crashed quickly with `calc_tsfc = .false.`

**Comment by kieranricardo** [comment]
@MartinDix weirdly this causing more instability issues

**Comment by kieranricardo** [comment]
Working now!
