### ISSUE TITLE
Move UM code and suite to github.

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/dev_coupling#20]
Follow CABLE AM3 development and move to a private github repo.

**Comment by MartinDix** [comment]
dev_coupling_um and dev_coupling_suite?

**Comment by MartinDix** [comment]
To get a git version starting at vn13.0
`git svn clone -r 111272:HEAD --branches=branches/dev/kieranricardo/vn13.0_nuopc  file:///g/data/ki32/mosrs/um/main`

**Comment by MartinDix** [comment]
Is there a way to put just the UM configuration in a private repo and have the rest public?

**Comment by aidanheerdegen** [comment]
> Is there a way to put just the UM configuration in a private repo and have the rest public?

Yes this is possible with `git submodules`. 

The private repo not be publicly visible, just the hash that it points to

https://stackoverflow.com/a/37638473

**Comment by kieranricardo** [comment]
@MartinDix and @aidanheerdegen I've made private [cm3-um](https://github.com/ACCESS-NRI/cm3-um) and [cm3-suite](https://github.com/ACCESS-NRI/cm3-suite) repos. 

For now I've kept everything in the suite private. Next step will be to make MOM6, CICE6, and nuopc configs public by adding them to a public repo, and linking with gitmodules submodules
