### ISSUE TITLE
Time average fluxes in CICE cap

### ISSUE THREAD

**Issue by kieranricardo** [ACCESS-NRI/dev_coupling#27]
CICE cap currently returns instantaneous fluxes - return fluxes averaged over time step instead.

**Comment by kieranricardo** [comment]
Added in https://github.com/ACCESS-NRI/CICE/commit/7809c2c509b175d41d8d7daa7ead611858120e5a

**Comment by aekiss** [comment]
@kieranricardo does this bug affect ice-ocean fluxes? ie should this fix also be used in ACCESS-OM3?
