### ISSUE TITLE
Sea ice problems

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/dev_coupling#31]
Comparing the `cm3-run-30-07-2024` run with the CM2 PD control `u-bz687`. These should start with the same ocean initial condition and sea ice area is initially the same.

![cm3_icearea](https://github.com/user-attachments/assets/3e13151d-d183-4ad3-93c0-77bc8eeb7a39)

Why does it fail to form in the SH winter?  Does the ocean not get cold enough or does the ocean cool and then something go strange with ice formation (e.g. something keeps melting it).

**Comment by MartinDix** [comment]
Even more dramatic SH difference for sea ice volume
![icevol](https://github.com/user-attachments/assets/6569ce51-c7ad-40d5-bc4d-aaab3ba7d1ed)

**Comment by MartinDix** [comment]
Averages over a part of the Weddell Sea show that the net surface flux from the UM is more negative in CM3, so why doesn't the ice increase?

![weddell_map](https://github.com/user-attachments/assets/bc31ed9c-6d67-4fd2-bbf7-91277b832d08)

![weddell](https://github.com/user-attachments/assets/f4b7ac59-5116-44b6-9a5d-66bae5b61590)

**Comment by MartinDix** [comment]
The CICE radiation fluxes seem to be zero over the ice, including the upwards LW, FLWUP. E.g. downwards SW  from `GMOM_JRA.cice.h.1981-07.nc`

![cice_fswdn](https://github.com/user-attachments/assets/95dfcd6c-0ebf-435b-a353-9943c18711f5)

**Comment by aekiss** [comment]
We don't see the sea ice vanishing in ACCESS-OM3 https://github.com/COSIMA/access-om3/issues/39#issuecomment-2232460831

**Comment by MartinDix** [comment]
The `scale-ice-fluxes` and `fix-airtemp` experiments don't make much  difference to the area means, though there are some local differences 

![icearea](https://github.com/user-attachments/assets/2d247bfa-5738-4dd0-99f8-ece040e51599)

![icevol](https://github.com/user-attachments/assets/49c47ae5-95ce-462f-9601-d5c46e27e261)

![ice_depth_s](https://github.com/user-attachments/assets/93b7ac48-6268-4ac0-a4ff-eb29011fa0cd)

**Comment by MartinDix** [comment]
The scaled-flux run saves some extra flux diagnostics from MOM, though they're not quite identical (in name at least) to those saved from CM2. Now averaging over a smaller Weddell sea region at the edge of where ice forms in the CM3 run

![weddell2](https://github.com/user-attachments/assets/066aaea1-c4da-47c4-b549-9144a26fcdd2)

CM3 cools similarly to CM2, suggesting there's no problem with the open ocean fluxes. However when at freezing ice fails to form at the same rate for some reason.

![weddell_comparison](https://github.com/user-attachments/assets/f65bce0c-5dbe-4c72-b08d-30abe05e3811)

**Comment by MartinDix** [comment]
`fsurf_ai` and `fcondtop_ai` are saved.

**Comment by anton-seaice** [comment]
If its useful for me to have a look, send me the path to the output :)

**Comment by MartinDix** [comment]
Monthly means gathered to a single directory `/scratch/tm70/mrd599/cylc-run/u-di851/cice_output`

**Comment by ofa001** [comment]
Had a quick look at fsurfn_ai and fcondtopn_ai in this u-di851 run first 2 years against the 1st year of the CM2 run di702 where I your run has only  1 year of data,  the runs quickly diverge, and the CM2 retains ice in thicker categories, has higher fluxes in these categories fluxes by a up to 2~5Wm-2  depending on month, but its not clear which comes first.   Looking at monthly data.  The daily CM2 data doesn't have the data split by categories with the flux data, but we could run that way if we thought it would help.

**Comment by kieranricardo** [comment]
Sea-ice issues fixed by increasing ice and snow thickness limits to CM2 values, and using the correct UM surface flux.
 
![Image](https://github.com/user-attachments/assets/f4a735dc-ce7e-45fb-a25a-a953da032113)
![Image](https://github.com/user-attachments/assets/57f53050-f19a-41e8-8728-683af86d4155)
