### ISSUE TITLE
Inconsistency between UM and mediator precipitation

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/dev_coupling#40]
From one year of `cm3-run-09-10-2024-control` (essentially the same results from `cm3-run-24-09-2024-fix-wind-stress`) the ocean precipitation from the UM monthly STASH diagnostics differs from the NUOPC mediator diagnostics. Other components of the water budget like evaporation, sublimation and river outflow don't show the same differences. Even more strangely the convective and large scale precipitation differences are different.

Mediator rain = `atmImp_Faxa_rainc + atmImp_Faxa_rainl`
Mediator snow = `atmImp_Faxa_snowc + atmImp_Faxa_snowl`
Mediator evaporation = `atmImp_Foxx_evap`

UM rain = STASH 4203 + 5205 = 5214
UM snow = STASH 4204 + 5206 = 5215
UM total precip = STASH 5216
UM evaporation over open ocean = STASH 3232

Global totals kg/year
| Term | Mediator | UM |
| - | - | - |
| Evap | 4.883e17 | 4.883e17 |
| Precip | 4.381e17 | 4.358e17 |
| Sublimation | 9.0e14 | 9.0e14 |
| River outflow | 4.34e16 | 4.34e16 |

The precipitation difference is from rain rather than snow
| Term | Mediator | UM |
| - | - | - |
| Large scale | 8.933e16 | 8.789e16 |
| Convective | 3.206e17 | 3.198e17 |

   
![um_med_diff](https://github.com/user-attachments/assets/e6684e45-6ad7-4670-80b5-1d648e2c4a14)
![um_med_diff_rain](https://github.com/user-attachments/assets/d62bd444-e4df-46ab-bf6e-cf9a376a2a41)

There are large scale rain differences in the tropics, though the LS rain itself is small there.

![um_med_diff_rain_zon](https://github.com/user-attachments/assets/7e61e564-a39c-4e31-8115-16dacfb1e4e7)

**Comment by anton-seaice** [comment]
So the rain over land looks ok by the sounds of it ?

I guess you have checked the field names are mapped correctly, and the remapping [technique](https://escomp.github.io/CMEPS/versions/master/html/esmflds.html?highlight=route%20handle#addmap) looks ok ?

**Comment by MartinDix** [comment]
Zonal means weren't masking the land properly. Corrected version doesn't change things much.

![um_med_diff_rain_zon](https://github.com/user-attachments/assets/98c66859-56d8-462b-8561-cceab7462bd9)

**Comment by MartinDix** [comment]
For a basic sanity check I modified the UM to set the large scale rain to a constant 1e-5 and convective rain to 2e-5. Mediator fields matched very closely (relative differences O(1e-8)), consistent with UM diagnostics being 32 bit and mediator 64 bit.

Suggests it's something to do with the spatial or time averaging. Both the spatial and temporal variability of the evaporation will be less than the precipitation, but hard to see why large scale and convective would behave differently.

**Comment by MartinDix** [comment]
I modified the suite to save daily mean rainfall from the UM. The monthly mean of this matches the mediator and so is different to the UM monthly mean file. Something strange in the UM stash mean processing?

**Comment by MartinDix** [comment]
In the  CM3 suite um/rose-app.conf has 
```
[namelist:umstash_time(tmonm_eb9a649b)]
...
unt2=2
```

This means it's sampling once per hour. It should have `unt2=1` to sample every step.

This was inadvertently changed way back in the initial NUOPC test suite, 
https://code.metoffice.gov.uk/trac/roses-u/changeset/250354/c/q/5/7/6/trunk/app

This would have also affected evaporation but perhaps because that's less variable in time the difference wasn't as significant. Also a mystery why this lead to a mean difference in the rainfall rather than purely random errors. These runs have radiation calculated every step. UKCA is called only one per hour so perhaps there's an influence from the aerosol calculation?

Note that this only affects the UM diagnostics, not the actual coupling.

**Comment by MartinDix** [comment]
From a one year run with this fixed

Global ocean totals in kg/year

| Term | Mediator | UM |
| -- | -- | -- |
| Evap  | 4.8867e+17 | 4.8867e+17 |
| Precip | 4.3794e+17 | 4.3794e+17 |

The evaporation difference is several orders of magnitude smaller than before
![um_med_diff](https://github.com/user-attachments/assets/e9483745-5cf5-496d-a18d-ef0f821851ff)
