### ISSUE TITLE
UM outputs -1.1120897e+09 instead of NaNs over land

### ISSUE THREAD

**Issue by kieranricardo** [ACCESS-NRI/dev_coupling#46]
The UM appears to be diving by 28 instead of 29 on leap years when calculating monthly means.

This was first noticed in the SW and LW fields `fld_s01i203` in `/scratch/tm70/kr4383/cylc-run/cm3-run-06-11-2024-radiation-balance-ice-detrainment/share/data/History_Data/netCDF/atmosa.pm1984feb.nc`. Missing values are `-2**30 * 29 /28` instead `-2**30`. Haven't checked other fields.

**Comment by MartinDix** [comment]
See https://github.com/ACCESS-NRI/cm3-um/issues/2
