### ISSUE TITLE
Create proper land-sea mask

### ISSUE THREAD

**Issue by kieranricardo** [ACCESS-NRI/dev_coupling#7]

**Comment by MartinDix** [comment]
Suite u-cy780 now uses the OM3 1 degree ocean configuration with ocean mask `/g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mask.nc`.

This is slightly different to the 1 degree mask used by CM2 `~access/access-cm2/input_b/cpl_n96/oasis3_masks_N96_06032014.nc`. In particular the Red Sea is one grid point wider in the OM2 version. Therefore we can't use the UM ancillary files from CM2 but need to create new ones.

Suite u-cx958 generates the CM2 ancillaries from OM2 grid files. Set rose-suite.conf to use
```
HORIZ='n96e'
MODEL='n96e_mom1_20201102'
OCEAN='MOM1'
OCEAN_GRID_DIR='/g/data/ik11/inputs/access-om2/input_20201102'
```

This CM2 suite doesn't generate soil roughness so disable that for now (see u-da953).

Need the GAL9 ancillary suite u-cp883 for soil roughness.

**Comment by aekiss** [comment]
Note that this is not the final land mask for OM3, just an interim one for testing. At some point we intend to re-generate the topography and land mask to take full advantage of the C grid, which will make some straits narrower.
